[project]
name = "adv-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "canvasapi>=3.3.0",
    "dotenv>=0.9.9",
    "markdown>=3.8.2",
    "requests>=2.32.4",
]
